# Generated by Django 3.2.5 on 2021-07-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='c_option1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='polls',
            name='c_option2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='polls',
            name='c_option3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='polls',
            name='c_option4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='polls',
            name='c_option5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='polls',
            name='option1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='polls',
            name='option2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='polls',
            name='option3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='polls',
            name='option4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='polls',
            name='option5',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
